import colorsys
import re
from typing import Tuple

from typedefs import ThemePalette

# Lightness deltas (in 0-1 range) measured from the Blue Robotics palette:
#   BR_BLUE       #2699D0  L=0.48  (light anchor)
#   MARINER_BLUE  #135DA3  L=0.36  (mid anchor / primary)
#   BLUE_WHALE    #012F46  L=0.14  (dark anchor)
# We treat the user color as the mid anchor and derive the others.
LIGHT_DELTA = 0.12
DARK_DELTA = -0.22

HEX_RE = re.compile(r"^#?([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$")


def normalize_hex(value: str) -> str:
    match = HEX_RE.match(value.strip())
    if not match:
        raise ValueError(f"Invalid hex color: {value!r}")
    raw = match.group(1)
    if len(raw) == 3:
        raw = "".join(ch * 2 for ch in raw)
    return f"#{raw.upper()}"


def hex_to_rgb(value: str) -> Tuple[float, float, float]:
    hex_str = normalize_hex(value)[1:]
    r = int(hex_str[0:2], 16) / 255
    g = int(hex_str[2:4], 16) / 255
    b = int(hex_str[4:6], 16) / 255
    return r, g, b


def rgb_to_hex(r: float, g: float, b: float) -> str:
    ri = max(0, min(255, round(r * 255)))
    gi = max(0, min(255, round(g * 255)))
    bi = max(0, min(255, round(b * 255)))
    return f"#{ri:02X}{gi:02X}{bi:02X}"


def shift_lightness(value: str, delta: float) -> str:
    r, g, b = hex_to_rgb(value)
    h, lightness, s = colorsys.rgb_to_hls(r, g, b)
    new_l = max(0.0, min(1.0, lightness + delta))
    nr, ng, nb = colorsys.hls_to_rgb(h, new_l, s)
    return rgb_to_hex(nr, ng, nb)


def derive_palette(primary_color: str) -> ThemePalette:
    mid = normalize_hex(primary_color)
    return ThemePalette(
        light=shift_lightness(mid, LIGHT_DELTA),
        mid=mid,
        dark=shift_lightness(mid, DARK_DELTA),
    )


def render_theme_css(palette: ThemePalette) -> str:
    """Render the override stylesheet that replaces BlueOS gradient anchors and primary color.

    The frontend's index.html unconditionally loads /userdata/styles/theme_style.css.
    We override the same CSS variables and glass classes used by App.vue.
    """
    light = palette.light
    mid = palette.mid
    dark = palette.dark
    return (
        "/* Generated by BlueOS customization service. Do not edit by hand. */\n"
        ":root {\n"
        f"  --v-br_blue-base: {light};\n"
        f"  --v-mariner_blue-base: {mid};\n"
        f"  --v-blue_whale-base: {dark};\n"
        f"  --v-primary-base: {mid};\n"
        f"  --v-water-base: {light};\n"
        f"  --v-detail-base: {dark};\n"
        f"  --v-secondary-base: {dark};\n"
        "}\n"
        "\n"
        ".light-background-glass {\n"
        f"  background-color: {light}55 !important;\n"
        f"  background-image: linear-gradient(160deg, {light}88 0%, {mid}88 100%) !important;\n"
        "}\n"
        "\n"
        ".dark-background-glass {\n"
        f"  background-color: {mid}55 !important;\n"
        f"  background-image: linear-gradient(160deg, {mid}88 0%, {dark}88 100%) !important;\n"
        "}\n"
    )
